// components/Footer.vue
<template>
    <div class="flex flex-col" data-aos="fade-up" data-aos-delay="50">
        <div class="bg-secondary p-10 sm:p-20 w-full rounded-t-xl flex flex-col gap-10 lg:flex-row items-start justify-between">
            <div class="flex flex-col gap-2">
                <img :src="footerLogo" class="size-10" />
                <span class="mb-5 text-white-alt font-bold text-2xl">Lucas Boinet</span>

                <div class="flex flex-col gap-1">
                    <span class="text-sm text-gray-400">Email</span>
                    <span class="text-white-alt">lucasboinet.pro@gmail.com</span>
                </div>
            </div>

            <span class="block lg:hidden w-full h-[1px] bg-white-alt bg-opacity-30"></span>

            <div class="flex flex-col items-end gap-6 w-full lg:max-w-96">
                <span class="font-bold text-2xl text-white-alt w-full text-center lg:text-right">Contactez-moi sans attendre pour parler de votre projet</span>

                <a href="#contact" class="mx-auto lg:mx-0 alig">
                    <button class="bg-primary text-white-alt rounded-lg px-12 py-3 text-xs font-medium">Contact</button>
                </a>
            </div>
        </div>

        <div class="bg-primary bg-opacity-70 text-background-dark flex flex-col md:flex-row justify-between items-center px-20 py-5 text-sm">
            <span class="text-center">© {{ new Date().getFullYear() }} Lucas Boinet, All rights reserved.</span>

            <!-- <a href="#" class="hover:underline text-center">Conditions générales de vente</a> -->
        </div>
    </div>
</template>

<script lang="ts" setup>
import footerLogo from "~/assets/img/logo.svg"
</script>

// components/footer.tsx
import GlowingOrb from "@/components/glowing-orb";
import Image from "next/image";
import Link from "next/link";

export default function Footer() {
    return (
        <div className="pb-6 pt-6">
            <div
                className="bg-background p-9 rounded-2xl relative overflow-hidden"
                data-aos="fade-up"
                data-aos-delay="100"
            >

                <div className="z-[1] flex items-start justify-between w-full">
                    <div className="flex flex-col gap-6 max-w-[425px]">
                        <Image src="/icons/logo.svg" alt="website logo" width={49} height={49} />

                        <p className="text-sm text-white">
                            Applications web & mobile ou encore site internet (e-commerce, vitrine, portfolio, blog, etc...). J’assure la prise en charge de votre besoin en développement web.
                        </p>

                        <div className="flex flex-row gap-4">
                            <Link href="https://www.linkedin.com/in/lucas-boinet/" target="_blank" className="bg-primary rounded-md p-2">
                                <Image src="/icons/linkedin.svg" alt="linkedin icon" width={14} height={14} />
                            </Link>
                        </div>
                    </div>
                    <span className="text-[10px] text-white">lucasboinet.pro@gmail.com</span>
                </div>

                <div className="z-[1] flex items-center justify-between w-full mt-14 text-[10px] text-white">
                    <span>© 2025 — Copyright Lucas Boinet</span>

                    <span>Designed by <Link href="https://www.hugoboinet.com" target="_blank" className="underline">Hugo Boinet</Link></span>
                </div>

                <GlowingOrb
                    className="absolute -bottom-20 left-1/2 transform -translate-x-1/2 w-1/2 blur-[150px] opacity-0"
                    style={{animation: "fadeIn 500ms ease-out forwards"}}
                />
            </div>
        </div>
    )
}
